network:
  api:
    akEndfield:
      appCode:
        osWinRel: YDUTE5gscDZ229CW
      launcherAppCode:
        osWinRel: TiaytKBUIEdoEwRT
      channel:
        osWinRel: 6
      base:
        accountService: YXMuZ3J5cGhsaW5lLmNvbQ==
        launcher: bGF1bmNoZXIuZ3J5cGhsaW5lLmNvbS9hcGk=
        u8: dTguZ3J5cGhsaW5lLmNvbQ==
  userAgent:
    minimum: Mozilla/5.0
    chromeWindows: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
      (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36
    curl: curl/8.4.0
    ios: Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15
      (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1
  timeout: 20000
  retryCount: 5
threadCount:
  network: 16
cli:
  autoExit: false
logger:
  logLevel: 0
  useCustomLayout: true
  customLayoutPattern: "%[%d{hh:mm:ss.SSS} %-5.0p >%] %m"
